# 打包后会排除该文件
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seezoon?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&connectTimeout=1000&socketTimeout=60000&rewriteBatchedStatements=true
    username: root
    password: