// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.seezoon.grpc.demo;

public interface HelloWorldRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.seezoon.grpc.demo.HelloWorldRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    String getName();

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();
}
