// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.seezoon.grpc.demo;

public interface HelloWorldResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.seezoon.grpc.demo.HelloWorldResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     *
     * @return The message.
     */
    String getMessage();

    /**
     * <code>string message = 1;</code>
     *
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString getMessageBytes();
}
